#!/usr/bin/env python3
"""Maintain a generated block between markers in a Markdown file.

Two generators need the same protocol — print the block, splice it into its file, or
fail when the committed copy is stale — and only what they generate differs. The
protocol has never varied; the two copies of it had drifted in nothing but the name
of their error class. A third consumer is foreseeable, which is what makes a copy
the wrong answer.

The repository root is threaded in rather than held here. Each generator resolves it
from its own location and the suites redirect a whole run by patching that value, so
a root owned here would both break that seam and silently point at the real
workspace during a test.

This module owns one error convention: raise, and let ``dispatch`` print
``FAIL <file> - <reason>``. That is not a departure from the entry points keeping
their own conventions — both consumers already share this one, and neither of the
two validators that must stay independently phrased is a consumer.

Standard library only.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path
from typing import Callable

from diagnostic_text import printable


class BlockError(Exception):
    """A failure to report as `FAIL <file> - <reason>` rather than a traceback."""


@dataclass(frozen=True)
class Markers:
    """The comment pair fencing one generated block, and who regenerates it."""

    name: str
    generator: str

    @property
    def start(self) -> str:
        return f"<!-- {self.name}:START (generated by {self.generator} — do not edit by hand) -->"

    @property
    def end(self) -> str:
        return f"<!-- {self.name}:END -->"


@dataclass(frozen=True)
class Rendered:
    """A block including its markers, plus any detail its OK line should carry.

    The block keeps its own internal layout: this module owns where a block begins
    and ends in the target, not how its body is spaced.
    """

    text: str
    detail: str = ""


def where(path: Path, root: Path) -> str:
    """The path as the diagnostics name it: relative to the repository root."""
    try:
        return str(path.relative_to(root))
    except ValueError:
        return str(path)


def read(path: Path, root: Path) -> str:
    try:
        return path.read_text(encoding="utf-8")
    except UnicodeError as error:
        raise BlockError(f"{where(path, root)} - must use UTF-8") from error
    except OSError as error:
        raise BlockError(f"{where(path, root)} - {error}") from error


def write(path: Path, text: str, root: Path) -> None:
    try:
        path.write_text(text, encoding="utf-8")
    except OSError as error:
        raise BlockError(f"{where(path, root)} - {error}") from error


def span(text: str, markers: Markers) -> tuple[int, int]:
    """The start/end offsets of the generated block, markers included.

    Each marker must appear exactly once. A duplicated pair used to leave the
    second copy untouched by --write and unnoticed by --check, which is the one
    thing a generated block exists to prevent: it stayed stale in silence.
    """
    starts = text.count(markers.start)
    ends = text.count(markers.end)
    if not starts or not ends:
        raise ValueError(f"{markers.name} markers not found")
    if starts > 1 or ends > 1:
        raise ValueError(f"{markers.name} markers must appear exactly once")
    start = text.index(markers.start)
    end = text.index(markers.end, start) + len(markers.end)
    return start, end


@dataclass(frozen=True)
class Block:
    """One generated block, bound to the root a run resolved."""

    root: Path
    relative: Path
    markers: Markers
    label: str

    @property
    def target(self) -> Path:
        return self.root / self.relative

    def sync(self, args: argparse.Namespace, rendered: Rendered) -> int:
        """Print the block, splice it in, or fail because the committed copy is stale."""
        if not (args.write or args.check):
            print(rendered.text)
            return 0

        target = self.target
        shown = where(target, self.root)

        # Rendered.text is documented as including its markers, and splicing a body
        # that does not would delete them from the target — detectable only by the
        # next --check, after the damage. A third consumer is foreseeable.
        if not (
            rendered.text.startswith(self.markers.start)
            and rendered.text.endswith(self.markers.end)
        ):
            raise BlockError(f"{shown} - the rendered {self.label} is missing its own markers")

        current = read(target, self.root)

        try:
            start, end = span(current, self.markers)
        except ValueError as error:
            reason = str(error) if str(error) else f"{self.markers.name} markers not found"
            raise BlockError(f"{shown} - {reason}") from None

        if current[start:end] == rendered.text:
            detail = f" {rendered.detail}" if rendered.detail else ""
            print(printable(f"OK   {shown} {self.label}{detail}"))
            return 0

        if args.check:
            raise BlockError(
                f"{shown} - the {self.label} block is out of date; "
                f"run .venv/bin/python {self.markers.generator} --write"
            )

        write(target, current[:start] + rendered.text + current[end:], self.root)
        print(printable(f"OK   rewrote the {self.label} in {shown}"))
        return 0


def dispatch(
    argv: list[str] | None,
    run: Callable[[argparse.Namespace], int],
    *,
    description: str,
    label: str,
) -> int:
    """Parse the three modes and report a BlockError as a diagnostic, not a traceback."""
    parser = argparse.ArgumentParser(description=description)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--write", action="store_true", help=f"splice the {label} into its file")
    mode.add_argument("--check", action="store_true", help=f"fail if the {label} is out of date")
    args = parser.parse_args(argv)

    try:
        return run(args)
    except BlockError as error:
        print(printable(f"FAIL {error}"))
        return 1
