#!/usr/bin/env python3
"""Generate the record inventory for every producer→consumer seam between skills.

A seam is a skill whose `**Input**:` line names another skill and the record that skill
produces, in the phrasing `AGENTS.md` mandates and `skill_model.CONSUMES` recognises. The
list is **derived** rather than maintained, so "one seam" is what the corpus says today and
a second one is counted without editing anything here — the same reason the README skill
maps come from each skill's handoffs rather than from a list somebody keeps.

Zero seams is a clean answer, not a failure. A check that failed on none would become a
reason to keep a seam alive, which is the opposite of what this is for.

**What this does not observe.** It does not judge whether each element the producer emits is
read, nor whether the consumer names an element the producer never writes. Those are the two
defects this repository found by hand, and both were found by reading an inventory beside the
prose that described it — not by an assertion a script could make without guessing which of a
producer's fields a consumer is obliged to care about. The inventory is generated so that it
cannot go stale while the prose beside it does; reconciling the two stays a human act.

The block lives in docs/review-record-contract.md between the SEAM-INVENTORY markers.
Standard library only.

Usage:
    python3 scripts/seam_contract.py            # print the block to stdout
    python3 scripts/seam_contract.py --write    # splice it into the contract
    python3 scripts/seam_contract.py --check    # fail when the contract is out of date
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path

from skill_model import CONSUMES

ROOT = Path(__file__).resolve().parent.parent

CONTRACT = Path("docs/review-record-contract.md")

START = (
    "<!-- SEAM-INVENTORY:START (generated by scripts/seam_contract.py — do not edit by hand) -->"
)
END = "<!-- SEAM-INVENTORY:END -->"

INPUT_LINE = re.compile(r"^\*\*Input\*\*\s*:(.+)$", re.MULTILINE)
FENCE = re.compile(r"^```markdown\n(.*?)^```", re.MULTILINE | re.DOTALL)
HEADER_FIELD = re.compile(r"^\*\*([^*]+)\*\*\s*:", re.MULTILINE)
SECTION = re.compile(r"^#{2,3} (.+)$", re.MULTILINE)


class SeamError(Exception):
    """A failure to report as `FAIL <file> - <reason>` rather than a traceback."""


def where(path: Path) -> str:
    """The path as the diagnostics name it: relative to the repository root."""
    try:
        return str(path.relative_to(ROOT))
    except ValueError:
        return str(path)


def read(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8")
    except OSError as error:
        raise SeamError(f"{where(path)} - {error}") from error


def write(path: Path, text: str) -> None:
    try:
        path.write_text(text, encoding="utf-8")
    except OSError as error:
        raise SeamError(f"{where(path)} - {error}") from error


def elements(skill_md: str) -> list[tuple[str, str]]:
    """The record shape a producer states: its header fields, then its sections.

    Read from the fenced ```markdown block the skill uses for its output template, so a
    producer that states no template contributes nothing rather than a guess.
    """
    fence = FENCE.search(skill_md)

    if not fence:
        return []

    template = fence.group(1)

    return [(name.strip(), "field") for name in HEADER_FIELD.findall(template)] + [
        (name.strip(), "section") for name in SECTION.findall(template)
    ]


def load(skills_dir: Path):
    """Every seam the corpus declares, as (consumer, producer, record, elements)."""
    try:
        names = sorted(p.name for p in skills_dir.iterdir() if p.is_dir())
    except OSError as error:
        raise SeamError(f"{where(skills_dir)} - {error}") from error

    body = {name: read(skills_dir / name / "SKILL.md") for name in names}
    seams = []

    for consumer in names:
        declared = INPUT_LINE.search(body[consumer])

        if not declared:
            continue

        for producer, record in CONSUMES.findall(declared.group(1)):
            if producer in body and producer != consumer:
                seams.append((consumer, producer, record, elements(body[producer])))

    return seams


def render(seams) -> str:
    lines = [START]

    if not seams:
        lines.append(
            "\nNo skill's `**Input**:` line names another skill's record. Nothing to hold.\n"
        )
        lines.append(END)
        return "\n".join(lines)

    for consumer, producer, record, items in sorted(seams):
        lines.append(f"\n### `{producer}` → `{consumer}` — {record}\n")

        if not items:
            lines.append(
                f"`{producer}` states no output template, so it declares no record shape.\n"
            )
            continue

        lines.append("| Element | Kind |")
        lines.append("|---|---|")

        for name, kind in items:
            lines.append(f"| `{name}` | {kind} |")

        lines.append("")

    lines.append(END)
    return "\n".join(lines)


def block_span(text: str) -> tuple[int, int]:
    """Return the start/end offsets of the generated block, markers included."""
    start = text.index(START)
    end = text.index(END, start) + len(END)
    return start, end


def run(args: argparse.Namespace) -> int:
    seams = load(ROOT / "skills")
    block = render(seams)

    if not (args.write or args.check):
        print(block)
        return 0

    contract_path = ROOT / CONTRACT
    contract = read(contract_path)

    try:
        start, end = block_span(contract)
    except ValueError:
        raise SeamError(f"{where(contract_path)} - SEAM-INVENTORY markers not found") from None

    if contract[start:end] == block:
        print(f"OK   {where(contract_path)} seam inventory ({len(seams)} seam(s))")
        return 0

    if args.check:
        raise SeamError(
            f"{where(contract_path)} - seam inventory is out of date; "
            "run python3 scripts/seam_contract.py --write"
        )

    write(contract_path, contract[:start] + block + contract[end:])
    print(f"OK   rewrote the seam inventory in {where(contract_path)}")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate the seam record inventory.")
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--write", action="store_true", help="splice the inventory into the contract")
    mode.add_argument("--check", action="store_true", help="fail if the contract is out of date")
    args = parser.parse_args(argv)

    try:
        return run(args)
    except SeamError as error:
        print(f"FAIL {error}")
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
