#!/usr/bin/env python3
"""Generate per-domain skill maps (Mermaid) from skill families and handoffs.

Reads each skill's `family` from skill.yaml and its handoff targets from
SKILL.md, using the shared handoff pattern in skill_model.py, then prints
Markdown with one Mermaid flowchart per family. Cross-family edges appear as
bridges to nodes owned by another family. Standard library only.

The maps live in README.md between the SKILL-MAPS markers. `--write` splices
them in so the block never has to be pasted by hand; `--check` fails when the
committed block no longer matches the skills.

Usage:
    .venv/bin/python scripts/skill_graph.py            # print the maps Markdown to stdout
    .venv/bin/python scripts/skill_graph.py --write    # splice the maps into README.md
    .venv/bin/python scripts/skill_graph.py --check    # fail if README.md is out of date
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path

from skill_model import FAMILIES, HANDOFF

FAMILY = re.compile(r"^family\s*:\s*(.+?)\s*$", re.MULTILINE)

ROOT = Path(__file__).resolve().parent.parent

START = "<!-- SKILL-MAPS:START (generated by scripts/skill_graph.py — do not edit by hand) -->"
END = "<!-- SKILL-MAPS:END -->"


class MapError(Exception):
    """A failure to report as `FAIL <file> - <reason>` rather than a traceback."""


def where(path: Path) -> str:
    """The path as the diagnostics name it: relative to the repository root."""
    try:
        return str(path.relative_to(ROOT))
    except ValueError:
        return str(path)


def read(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8")
    except OSError as error:
        raise MapError(f"{where(path)} - {error}") from error


def write(path: Path, text: str) -> None:
    try:
        path.write_text(text, encoding="utf-8")
    except OSError as error:
        raise MapError(f"{where(path)} - {error}") from error


def load(skills_dir: Path):
    try:
        names = sorted(p.name for p in skills_dir.iterdir() if p.is_dir())
    except OSError as error:
        raise MapError(f"{where(skills_dir)} - {error}") from error

    family: dict[str, str | None] = {}

    for name in names:
        match = FAMILY.search(read(skills_dir / name / "skill.yaml"))
        family[name] = match.group(1).strip().strip("'\"") if match else None

    edges: list[tuple[str, str]] = []

    for name in names:
        for target in sorted(set(HANDOFF.findall(read(skills_dir / name / "SKILL.md")))):
            if target in family:
                edges.append((name, target))

    return names, family, edges


def render(names, family, edges) -> str:
    lines = [START]

    for fam, title in FAMILIES.items():
        members = [n for n in names if family.get(n) == fam]

        if not members:
            continue

        lines.append(f"\n### {title}\n")
        lines.append("```mermaid")
        lines.append("flowchart LR")

        for name in members:
            lines.append(f"    {name}")

        for source, target in edges:
            if family.get(source) == fam:
                lines.append(f"    {source} --> {target}")

        lines.append("```")

    lines.append(f"\n{END}")
    return "\n".join(lines)


def block_span(readme: str) -> tuple[int, int]:
    """Return the start/end offsets of the generated block, markers included."""
    start = readme.index(START)
    end = readme.index(END, start) + len(END)
    return start, end


def run(args: argparse.Namespace) -> int:
    names, family, edges = load(ROOT / "skills")
    block = render(names, family, edges)

    if not (args.write or args.check):
        print(block)
        return 0

    readme_path = ROOT / "README.md"
    readme = read(readme_path)

    try:
        start, end = block_span(readme)
    except ValueError:
        raise MapError(f"{where(readme_path)} - SKILL-MAPS markers not found") from None

    if readme[start:end] == block:
        print(f"OK   {where(readme_path)} skill maps")
        return 0

    if args.check:
        raise MapError(
            f"{where(readme_path)} - skill maps are out of date; "
            "run .venv/bin/python scripts/skill_graph.py --write"
        )

    write(readme_path, readme[:start] + block + readme[end:])
    print(f"OK   rewrote the skill maps in {where(readme_path)}")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate the README skill maps.")
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--write", action="store_true", help="splice the maps into README.md")
    mode.add_argument("--check", action="store_true", help="fail if README.md is out of date")
    args = parser.parse_args(argv)

    try:
        return run(args)
    except MapError as error:
        print(f"FAIL {error}")
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
