#!/usr/bin/env python3
"""Generate per-domain skill maps (Mermaid) from skill families and handoffs.

Reads each skill's `family` from skill.yaml and its handoff targets from
SKILL.md (hand off to / point to / route to `<skill>`), then prints Markdown
with one Mermaid flowchart per family. Cross-family edges appear as bridges to
nodes owned by another family. Standard library only.

Usage:
    python3 scripts/skill_graph.py            # print the maps Markdown to stdout
"""

from __future__ import annotations

import re
from pathlib import Path

HANDOFF = re.compile(r"(?:hand off to|point to|route to)\s+`([a-z0-9-]+)`", re.IGNORECASE)
FAMILY = re.compile(r"^family\s*:\s*(.+?)\s*$", re.MULTILINE)

FAMILY_ORDER = ["implementation", "knowledge", "decisions", "meta"]
FAMILY_TITLE = {
    "implementation": "Implementation",
    "knowledge": "Knowledge",
    "decisions": "Decisions & governance",
    "meta": "Meta (skills about the toolkit)",
}

START = "<!-- SKILL-MAPS:START (generated by scripts/skill_graph.py — do not edit by hand) -->"
END = "<!-- SKILL-MAPS:END -->"


def load(skills_dir: Path):
    names = sorted(p.name for p in skills_dir.iterdir() if p.is_dir())
    family: dict[str, str | None] = {}

    for name in names:
        manifest = (skills_dir / name / "skill.yaml").read_text(encoding="utf-8")
        match = FAMILY.search(manifest)
        family[name] = match.group(1).strip().strip("'\"") if match else None

    edges: list[tuple[str, str]] = []

    for name in names:
        body = (skills_dir / name / "SKILL.md").read_text(encoding="utf-8")
        for target in sorted(set(HANDOFF.findall(body))):
            if target in family:
                edges.append((name, target))

    return names, family, edges


def render(names, family, edges) -> str:
    lines = [START]

    for fam in FAMILY_ORDER:
        members = [n for n in names if family.get(n) == fam]

        if not members:
            continue

        lines.append(f"\n### {FAMILY_TITLE.get(fam, fam)}\n")
        lines.append("```mermaid")
        lines.append("flowchart LR")

        for name in members:
            lines.append(f"    {name}")

        for source, target in edges:
            if family.get(source) == fam:
                lines.append(f"    {source} --> {target}")

        lines.append("```")

    lines.append(f"\n{END}")
    return "\n".join(lines)


def main() -> int:
    root = Path(__file__).resolve().parent.parent
    names, family, edges = load(root / "skills")
    print(render(names, family, edges))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
