#!/usr/bin/env python3
"""Generate per-domain skill maps (Mermaid) from skill families and handoffs.

Reads each skill's `family` from skill.yaml and its handoff targets from
SKILL.md, using the shared handoff pattern in skill_model.py, then prints
Markdown with one Mermaid flowchart per family. Cross-family edges appear as
bridges to nodes owned by another family. Standard library only.

The maps live in README.md between the SKILL-MAPS markers. `--write` splices
them in so the block never has to be pasted by hand; `--check` fails when the
committed block no longer matches the skills.

Usage:
    python3 scripts/skill_graph.py            # print the maps Markdown to stdout
    python3 scripts/skill_graph.py --write    # splice the maps into README.md
    python3 scripts/skill_graph.py --check    # fail if README.md is out of date
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path

from skill_model import FAMILIES, HANDOFF

FAMILY = re.compile(r"^family\s*:\s*(.+?)\s*$", re.MULTILINE)

START = "<!-- SKILL-MAPS:START (generated by scripts/skill_graph.py — do not edit by hand) -->"
END = "<!-- SKILL-MAPS:END -->"


def load(skills_dir: Path):
    names = sorted(p.name for p in skills_dir.iterdir() if p.is_dir())
    family: dict[str, str | None] = {}

    for name in names:
        manifest = (skills_dir / name / "skill.yaml").read_text(encoding="utf-8")
        match = FAMILY.search(manifest)
        family[name] = match.group(1).strip().strip("'\"") if match else None

    edges: list[tuple[str, str]] = []

    for name in names:
        body = (skills_dir / name / "SKILL.md").read_text(encoding="utf-8")
        for target in sorted(set(HANDOFF.findall(body))):
            if target in family:
                edges.append((name, target))

    return names, family, edges


def render(names, family, edges) -> str:
    lines = [START]

    for fam, title in FAMILIES.items():
        members = [n for n in names if family.get(n) == fam]

        if not members:
            continue

        lines.append(f"\n### {title}\n")
        lines.append("```mermaid")
        lines.append("flowchart LR")

        for name in members:
            lines.append(f"    {name}")

        for source, target in edges:
            if family.get(source) == fam:
                lines.append(f"    {source} --> {target}")

        lines.append("```")

    lines.append(f"\n{END}")
    return "\n".join(lines)


def block_span(readme: str) -> tuple[int, int]:
    """Return the start/end offsets of the generated block, markers included."""
    start = readme.index(START)
    end = readme.index(END, start) + len(END)
    return start, end


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate the README skill maps.")
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--write", action="store_true", help="splice the maps into README.md")
    mode.add_argument("--check", action="store_true", help="fail if README.md is out of date")
    args = parser.parse_args(argv)

    root = Path(__file__).resolve().parent.parent
    names, family, edges = load(root / "skills")
    block = render(names, family, edges)

    if not (args.write or args.check):
        print(block)
        return 0

    readme_path = root / "README.md"
    readme = readme_path.read_text(encoding="utf-8")

    try:
        start, end = block_span(readme)
    except ValueError:
        print(f"FAIL {readme_path.name} - SKILL-MAPS markers not found")
        return 1

    if readme[start:end] == block:
        print(f"OK   {readme_path.name} skill maps")
        return 0

    if args.check:
        print(
            f"FAIL {readme_path.name} - skill maps are out of date; "
            "run python3 scripts/skill_graph.py --write"
        )
        return 1

    readme_path.write_text(readme[:start] + block + readme[end:], encoding="utf-8")
    print(f"OK   rewrote the skill maps in {readme_path.name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
